spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/barbershop_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Driver e Dialetto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate: crea le tabelle automaticamente se non esistono
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL nel terminale per debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true