spring.application.name=backend

# Connessione al database MySQL online su FreeSQLDatabase
spring.datasource.url=jdbc:mysql://sql8.freesqldatabase.com:3306/sql8833797?serverTimezone=UTC
spring.datasource.username=sql8833797
spring.datasource.password=dIZhIsGNk5

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate: gestisce le tabelle (lasciamo 'update' visto che le hai già create tu su phpMyAdmin)
spring.jpa.hibernate.ddl-auto=update

# Mostra le query SQL nel terminale per debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true